# Generated by Django 3.0.5 on 2020-10-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(default='', max_length=50)),
                ('date1', models.DateField(null=True)),
                ('labels', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('priority', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
